const docs = [
	{
		type: 'doc',
		id: 'introduction',
		label: 'Introduction',
	},
	{
		type: 'doc',
		id: 'faq',
		label: 'Frequently Asked Questions',
	},
	{
		type: 'category',
		label: 'Guides',
		items: [
			{
				type: 'autogenerated',
				dirName: 'guides',
			},
		],
	},
	{
		type: 'category',
		label: 'Commands',
		items: [
			{
				type: 'autogenerated',
				dirName: 'commands',
			},
		],
	},
];

module.exports = { docs };
